config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"

  get '/change_password' => 'home#edit_password'
  post '/change_password' => 'home#update_password'
  get '/fast_alias' => 'aliases#fast_alias'
  post '/fast_alias' => 'aliases#fast_alias_creation'
  resources :domains, constraints: { id: /[^\/]+(?=\.html\z|\.json\z)|[^\/]+/ } do
    resources :aliases
    resources :groups
    resources :people
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/aliases_controller.rb
class AliasesController < ApplicationController
  before_action :get_alias, only: [:show, :edit, :update, :destroy]

  # GET /domains/domainname/aliases
  def index
    @aliases = @domain.aliases
  end

  # GET /domains/domainname/aliases/1
  def show
  end

  # GET /domains/domainname/aliases/new
  def new
    @alias = Alias.new
  end

  # GET /domains/domainname/aliases/1/edit
  def edit
  end

  # POST /domains/domainname/aliases/1
  def create
    @alias = Alias.new(domain: @domain)
    if @alias.update_attributes(alias_params)
      redirect_to domain_aliases_path(@domain), notice: t('aliases.creation-ok')
    else
      render :new
    end
  end

  # PUT /domains/domainname/aliases/1
  def update
    if @alias.update_attributes(alias_params)
      redirect_to domain_aliases_path(@domain), notice: t('aliases.edition-ok')
    else
      render :edit
    end
  end

  # DELETE /domains/domainname/aliases/1
  def destroy
    if @alias.destroy
      redirect_to domain_aliases_path(@domain), notice: t('aliases.deletion-ok')
    else
      render :edit
    end
  end

  def fast_alias
    @current_page = t('aliases.actions.fast-alias')
    @alias = Alias.new
  end

  def fast_alias_creation
    @current_page = t('aliases.actions.fast-alias')
    @alias = Alias.create_random_alias current_user, 'crta.me'
    render :fast_alias
  end

  private

  def get_alias
    @alias = Alias.find params[:id], base: @domain.dn
  end

  def alias_params
    params.require(:alias).permit( :mail, :cn, :maildrop, :description )
  end

end

app/views/aliases/_form.html.erb
<% if @alias.new_record?
  submit_text = t('aliases.actions.create')
  submit_url = domain_aliases_path(@domain.id)
  submit_method = 'post'
else
  submit_text = t('aliases.actions.update')
  submit_url = domain_alias_path(@domain.id, @alias.id)
  submit_method = 'put'
end %>

<%= form_with url: submit_url, method: submit_method, local: true do %>
  <%= render partial: 'layouts/errors', locals: {object: @alias} %>
  <div class="col-md-10 col-xs-12">
    <div class="row form-group mt-2" title="<%= t('ldap.descriptions.mail') %>">
      <div class="col-md-3 col-xs-12 text-md-right font-weight-bold">* <%= t("aliases.name") %>:</div>
      <div class="col-md-8 col-xs-12">
        <%= email_field :alias, :mail, class: "form-control", required: true, disabled: !@alias.new_record? %>
      </div>
    </div>
    <div class="row form-group" title="<%= t('ldap.descriptions.maildrop') %>">
      <div class="col-md-3 col-xs-12 text-md-right font-weight-bold">* <%= t("ldap.attributes.maildrop") %>:</div>
      <div class="col-md-8 col-xs-12">
        <%= text_field :alias, :maildrop, class: "form-control", required: true %>
      </div>
    </div>
    <div class="row form-group" title="<%= t('ldap.descriptions.cn') %>">
      <div class="col-md-3 col-xs-12 text-md-right font-weight-bold"><%= t("ldap.attributes.cn") %>:</div>
      <div class="col-md-8 col-xs-12">
        <%= text_field :alias, :cn, class: "form-control" %>
      </div>
    </div>
    <div class="row form-group" title="<%= t('ldap.descriptions.description') %>">
      <div class="col-md-3 col-xs-12 text-md-right font-weight-bold"><%= t("ldap.attributes.description") %>:</div>
      <div class="col-md-8 col-xs-12">
        <%= text_field :alias, :description, class: "form-control" %>
      </div>
    </div>
    <div class="float-right">
      <%= submit_tag(submit_text) %>
    </div>
  </div>
<% end %>

app/views/aliases/edit.html.erb
<% @current_page = t('aliases.actions.edit')%[@alias.id] %>
<%= render partial: 'form' %>

app/views/aliases/fast_alias.html.erb
<% if @alias.mail %>
  <div class="alert alert-success col-xs-12" role="alert">
    <div id="explanation" class="text-align-center">
      <h2>
        <%= I18n.t('aliases.fast-alias-creation-ok')%[@alias.mail] %>
      </h2>
    </div>
  </div>
<% else %>
  <%= form_with url: fast_alias_path, method: :post, local: true do %>
    <%= render partial: 'layouts/errors', locals: {object: @alias} %>
    <div class="col-md-10 col-xs-12">
      <div class="float-right">
        <%= submit_tag(t('aliases.actions.fast-alias')) %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/aliases/index.html.erb
<% @current_page = t('domains.mail-aliases') %>
<% if @aliases.any? %>
  <table id="aliases-table"
         data-page-length='25'
         class="table table-striped table-bordered table-hover data-table">
    <thead>
      <tr>
        <th><%= t("ldap.attributes.mail") %></th>
        <th><%= t("ldap.attributes.cn") %></th>
        <th><%= t("ldap.attributes.maildrop") %></th>
        <th data-orderable='false'>&nbsp;</th>
      </tr>
    </thead>
      <tbody>
        <% @aliases.each do |ali| %>
          <% show_url = domain_alias_path(@domain.id, ali.id) %>
          <% show_title = t('aliases.actions.show')%[ali.id] %>
          <tr>
            <td data-href="<%= show_url %>">
              <%= link_to(ali.mail, show_url, title: show_title) %>
            </td>
            <td data-href="<%= show_url %>" title="<%= ali.description %>">
              <%= ali.cn %>
            </td>
            <td data-href="<%= show_url %>">
              <%= ali.maildrop_as_string %>
            </td>
            <td class="text-right">
              <%= link_to icon('fa', 'edit'), edit_domain_alias_path(@domain.id, ali.id), title: t('aliases.actions.edit')%[ali.id] %>
              <%= link_to icon('fa', 'trash'), domain_alias_path(@domain.id, ali.id), method: :delete,
                          data: {confirm: t('aliases.actions.delete-confirm')%[ali.id]}, title: t('aliases.actions.delete')%[ali.id] %>
            </td>
          </tr>
        <% end %>
      </tbody>
  </table>
<% else %>
  <div class="row">
    <div class="col-md-12"><%= t('aliases.no-items') %></div>
  </div>
<% end %>

<div class="float-right mt-5">
  <%= link_to icon('fa', 'envelope', t('aliases.actions.new')), new_domain_alias_path(@domain.id), title: t('aliases.actions.new'), class: 'page-link' %>
</div>

<script>
  $(document).ready(function() {
    $("#aliases-table").dataTable();
  });
</script

app/views/aliases/new.html.erb
<% @current_page = t('aliases.actions.new') %>
<%= render partial: 'form' %>

app/views/aliases/show.html.erb
<% @current_page = @alias.id %>
<div class="row">
  <div class="col-md-10 col-xs-12">
    <div class="row mt-2">
      <div class="col-md-3 col-xs-12 text-md-right font-weight-bold"><%= t("aliases.name") %>:</div>
      <div class="col-md-8 col-xs-12"><%= @alias.id %></div>
    </div>
    <div class="row mt-2">
      <div class="col-md-3 col-xs-12 text-md-right font-weight-bold"><%= t("ldap.attributes.maildrop") %>:</div>
      <div class="col-md-8 col-xs-12"><%= @alias.maildrop_as_string %></div>
    </div>
    <div class="row mt-2">
      <div class="col-md-3 col-xs-12 text-md-right font-weight-bold"><%= t("ldap.attributes.cn") %>:</div>
      <div class="col-md-8 col-xs-12"><%= @alias.cn %></div>
    </div>
    <div class="row mt-2">
      <div class="col-md-3 col-xs-12 text-md-right font-weight-bold"><%= t("ldap.attributes.description") %>:</div>
      <div class="col-md-8 col-xs-12"><%= @alias.description %></div>
    </div>
  </div>
  <div class="float-right mt-5">
    <%= link_to icon('fa', 'envelope', t('actions.edit')), edit_domain_alias_path(@domain.id, @alias.id), title: t('aliases.actions.edit')%[@alias.id], class: 'page-link' %>
  </div>
</div>