config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"

  get '/change_password' => 'home#edit_password'
  post '/change_password' => 'home#update_password'
  get '/fast_alias' => 'aliases#fast_alias'
  post '/fast_alias' => 'aliases#fast_alias_creation'
  resources :domains, constraints: { id: /[^\/]+(?=\.html\z|\.json\z)|[^\/]+/ } do
    resources :aliases
    resources :groups
    resources :people
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/person.rb
class Person < LdapRecord
  PREFIX = "ou=People"
  include Dominable

  ldap_mapping dn_attribute: 'cn',
               classes: ['top', 'person', 'inetOrgPerson'],
               scope: :sub
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :get_person, only: [:show, :edit, :update, :destroy]

  # GET /domains/domainname/people
  def index
    @current_page = t('domains.people')
    @people = @domain.people
  end

  # GET /domains/domainname/people/1
  def show
    @current_page = @person.id
  end

  # GET /domains/domainname/people/new
  def new
    @current_page = t('people.actions.new')
  end

  # GET /domains/domainname/people/1/edit
  def edit
    @current_page = t('people.actions.edit')%[@person.id]
  end

  # POST /domains/domainname/people/1
  def create
  end

  # PUT /domains/domainname/people/1
  def update
  end

  # DELETE /domains/domainname/people/1
  def destroy
  end

  private

  def get_person
    @person = Person.find params[:id], base: @domain.dn
  end

  def person_params
  end

end

app/views/people/index.html.erb
<% if @people.any? %>
  <table id="people-table"
         data-page-length='25'
         class="table table-striped table-bordered table-hover data-table">
    <thead>
      <tr>
        <th><%= t("ldap.attributes.cn") %></th>
        <th><%= t("ldap.attributes.sn") %></th>
        <th><%= t("ldap.attributes.mail") %></th>
        <th data-orderable='false'>&nbsp;</th>
      </tr>
    </thead>
      <tbody>
        <% @people.each do |person| %>
          <% show_url = domain_person_path(@domain.id, person.id) %>
          <% show_title = t('people.actions.show')%[person.id] %>
          <tr>
            <td data-href="<%= show_url %>">
              <%= link_to(person.cn, show_url, title: show_title) %>
            </td>
            <td data-href="<%= show_url %>">
              <%= person.sn %>
            </td>
            <td data-href="<%= show_url %>">
              <%= person.mail if person.mail %>
            </td>
            <td class="text-right">
              <%= link_to icon('fa', 'edit'), edit_domain_person_path(@domain.id, person.id), title: t('people.actions.edit')%[person.id] %>
              <%= link_to icon('fa', 'trash'), domain_person_path(@domain.id, person.id), method: :delete,
                  data: {confirm: t('people.actions.delete-confirm')%[person.id]}, title: t('people.actions.delete')%[person.id] %>
            </td>
          </tr>
        <% end %>
      </tbody>
  </table>
<% else %>
  No people
<% end %>

<script>
  $(document).ready(function() {
    $("#people-table").dataTable();
  });
</script

app/views/people/show.html.erb
<% @current_page = @person.id %>
<div class="row">
  <div class="col-md-10 col-xs-12">
    <div class="row mt-2">
      <div class="col-md-3 col-xs-12 text-md-right font-weight-bold"><%= t("ldap.attributes.cn") %>:</div>
      <div class="col-md-8 col-xs-12"><%= @person.id %></div>
    </div>
    <div class="row mt-2">
      <div class="col-md-3 col-xs-12 text-md-right font-weight-bold"><%= t("ldap.attributes.sn") %>:</div>
      <div class="col-md-8 col-xs-12"><%= @person.sn %></div>
    </div>
    <div class="row mt-2">
      <div class="col-md-3 col-xs-12 text-md-right font-weight-bold"><%= t("ldap.attributes.mail") %>:</div>
      <div class="col-md-8 col-xs-12"><%= @person.mail %></div>
    </div>
    <div class="row mt-2">
      <div class="col-md-3 col-xs-12 text-md-right font-weight-bold"><%= t("ldap.attributes.description") %>:</div>
      <div class="col-md-8 col-xs-12"><%= @person.description %></div>
    </div>
  </div>
</div>