config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"

  get '/change_password' => 'home#edit_password'
  post '/change_password' => 'home#update_password'
  get '/fast_alias' => 'aliases#fast_alias'
  post '/fast_alias' => 'aliases#fast_alias_creation'
  resources :domains, constraints: { id: /[^\/]+(?=\.html\z|\.json\z)|[^\/]+/ } do
    resources :aliases
    resources :groups
    resources :people
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < LdapRecord
  PREFIX = "ou=Group"
  include Dominable

  ldap_mapping dn_attribute: 'cn',
               classes: ['groupOfNames'],
               scope: :sub

  before_validation(on: :save) do
    self.member ||= ''
  end

  def member_as_string
    self.member
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :get_group, only: [:show, :edit, :update, :destroy]

  # GET /domains/domainname/groups
  def index
    @groups = @domain.groups
  end

  # GET /domains/domainname/groups/1
  def show
  end

  # GET /domains/domainname/groups/new
  def new
    @group = Group.new
  end

  # GET /domains/domainname/groups/1/edit
  def edit
  end

  # POST /domains/domainname/groups/1
  def create
    @group = Group.new(domain: @domain)
    if @group.update_attributes(group_params)
      redirect_to domain_groups_path(@domain), notice: t('groups.creation-ok')
    else
      render :new
    end
  end

  # PUT /domains/domainname/aliases/1
  def update
    if @group.update(alias_params)
      redirect_to domain_groups_path(@domain), notice: t('groups.edition-ok')
    else
      render :edit
    end
  end

  # DELETE /domains/domainname/aliases/1
  def destroy
    if @group.destroy
      redirect_to domain_groups_path(@domain), notice: t('group.deletion-ok')
    else
      render :edit
    end
  end

  private

  def get_group
    @group = Group.find params[:id], base: @domain.dn
  end

  def group_params
    params.require(:group).permit( :cn, :description )
  end

end

app/views/groups/_form.html.erb
<% if @group.new_record?
  submit_text = t('groups.form.create-action')
  submit_url = domain_groups_path(@domain.id)
  submit_method = 'post'
else
  submit_text = t('groups.form.update-action')
  submit_url = domain_group_path(@domain.id, @group.id)
  submit_method = 'put'
end %>

<%= form_with url: submit_url, method: submit_method, local: true do %>
  <%= render partial: 'layouts/errors', locals: {object: @group} %>
  <div class="col-md-10 col-xs-12">
    <div class="row mt-2 form-group" title="<%= t('groups.form.cn-description') %>">
      <div class="col-md-3 col-xs-12 text-md-right font-weight-bold"><%= t("groups.name") %>:</div>
      <div class="col-md-8 col-xs-12">
        <%= email_field :group, :cn, class: "form-control", required: true, disabled: !@group.new_record? %>
      </div>
    </div>
    <div class="row form-group" title="<%= t('groups.form.member-description') %>">
      <div class="col-md-3 col-xs-12 text-md-right font-weight-bold"><%= t("ldap.attributes.member") %>:</div>
      <div class="col-md-8 col-xs-12">
        <%= text_field :group, :member, class: "form-control", required: true %>
      </div>
    </div>
    <div class="row form-group" title="<%= t('ldap.descriptions.description') %>">
      <div class="col-md-3 col-xs-12 text-md-right font-weight-bold"><%= t("ldap.attributes.description") %>:</div>
      <div class="col-md-8 col-xs-12">
        <%= text_field :group, :description, class: "form-control" %>
      </div>
    </div>
    <div class="float-right">
      <%= submit_tag(submit_text) %>
    </div>
  </div>
<% end %>

app/views/groups/edit.html.erb
<% @current_page = t('groups.actions.edit')%[@alias.id] %>
<%= render partial: 'form' %>

app/views/groups/index.html.erb
<% @current_page = t('domains.groups') %>
<% if @groups.any? %>
  <table id="groupss-table"
         data-page-length='25'
         class="table table-striped table-bordered table-hover data-table">
    <thead>
      <tr>
        <th><%= t("ldap.attributes.cn") %></th>
        <th><%= t("ldap.attributes.member") %></th>
        <th data-orderable='false'>&nbsp;</th>
      </tr>
    </thead>
      <tbody>
        <% @groups.each do |group| %>
          <% show_url = domain_group_path(@domain.id, group.id) %>
          <% show_title = t('groups.actions.show')%[group.id] %>
          <tr>
            <td data-href="<%= show_url %>">
              <%= link_to(group.cn, show_url, title: show_title) %>
            </td>
            <td data-href="<%= show_url %>">
              <%= group.member_as_string %>
            </td>
            <td class="text-right">
              <%= link_to icon('fa', 'edit'), edit_domain_group_path(@domain.id, group.id), title: t('groups.actions.edit')%[group.id] %>
              <%= link_to icon('fa', 'trash'), domain_group_path(@domain.id, group.id), method: :delete,
                           data: {confirm: t('groups.actions.delete-confirm')%[group.id]}, title: t('groups.actions.delete')%[group.id] %>
            </td>
          </tr>
        <% end %>
      </tbody>
  </table>
<% else %>
  <div class="row">
    <div class="col-md-12"><%= t('groups.no-items') %></div>
  </div>
<% end %>

<div class="float-right mt-5">
  <%= link_to icon('fa', 'group', t('groups.actions.new')), new_domain_group_path(@domain.id), title: t('groups.actions.new'), class: 'page-link' %>
</div>

<script>
  $(document).ready(function() {
    $("#groups-table").dataTable();
  });
</script

app/views/groups/new.html.erb
<% @current_page = t('groups.actions.new') %>
<%= render partial: 'form' %>

app/views/groups/show.html.erb
<% @current_page = @group.id %>
<div class="row">
  <div class="col-md-10 col-xs-12">
    <div class="row mt-2">
      <div class="col-md-3 col-xs-12 text-md-right font-weight-bold"><%= t("groups.name") %>:</div>
      <div class="col-md-8 col-xs-12"><%= @group.id %></div>
    </div>
    <div class="row mt-2">
      <div class="col-md-3 col-xs-12 text-md-right font-weight-bold"><%= t("ldap.attributes.member") %>:</div>
      <div class="col-md-8 col-xs-12"><%= @group.member_as_string %></div>
    </div>
    <div class="row mt-2">
      <div class="col-md-3 col-xs-12 text-md-right font-weight-bold"><%= t("ldap.attributes.description") %>:</div>
      <div class="col-md-8 col-xs-12"><%= @group.description %></div>
    </div>
  </div>
</div>