config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"

  get '/change_password' => 'home#edit_password'
  post '/change_password' => 'home#update_password'
  get '/fast_alias' => 'aliases#fast_alias'
  post '/fast_alias' => 'aliases#fast_alias_creation'
  resources :domains, constraints: { id: /[^\/]+(?=\.html\z|\.json\z)|[^\/]+/ } do
    resources :aliases
    resources :groups
    resources :people
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/domain.rb
class Domain < LdapRecord
  ldap_mapping dn_attribute: 'o',
               prefix: 'ou=Domains', classes: ['top', 'organization', 'domainRelatedObject'],
               scope: :one

  before_validation(on: :create) do
    self.destinationindicator = self.o if self.destinationindicator.blank?
    self.description = self.o if self.description.blank?
  end
  before_validation do
    self.associateddomain = self.o if self.associateddomain.blank?
  end

  # Create domain structure for people, aliases and groups
  after_create :create_domain_tree
  # Destroy domain structure before delete it
  before_destroy :can_destroy?, :destroy_domain_tree

  # Return all mail accounts of the domain
  def people
    Person.all base: dn
  end
  # Return all mail alias of the domain
  def aliases
    Alias.all base: dn
  end
  # Return all groups of the domain
  def groups
    Group.all base: dn
  end

  private

  # Build the full domain tree
  def create_domain_tree
    OrganizationalUnit.create ou: "Alias", domain: self
    OrganizationalUnit.create ou: "People", domain: self
    OrganizationalUnit.create ou: "Groups", domain: self
    # And the default groups
    #Group.create cn: "domain_admins", member: [current_user.ldap_dn], domain: self
  end

  # Validates if domain has no items on int and can be destroyed
  def can_destroy?
    if people.any? || aliases.any? || groups.any?
      errors.add(:base, I18n.t('errors.domain.destroy-with-items'))
    end
  end
  # Delete domain tree
  def destroy_domain_tree
    OrganizationalUnit.all(base: dn).each {|ou| ou.destroy} if errors.empty?
  end
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  before_action :get_domain, only: [:show, :edit, :update, :destroy]

  # GET /domains
  def index
    @domains = []
    # If current user is global admin, get all domains
    Domain.all.each do |domain|
      if current_user.is_global_admin? || current_user.is_domain_admin?(domain.dn.to_s)
        @domains.push domain
      end
    end
  end

  # GET /domains/1
  def show
  end

  # GET /domains/new
  def new
    @domain = Domain.new
  end

  # GET /domains/1/edit
  def edit
  end

  # POST /domains/1
  def create
    @domain = Domain.new
    if @domain.update_attributes(domain_params)
      redirect_to domains_path, notice: t('domains.creation-ok')
    else
      render :new
    end
  end

  # PUT /domains/1
  def update
    if @domain.update_attributes(domain_params)
      redirect_to domains_path, notice: t('domains.edition-ok')
    else
      render :edit
    end
  end

  # DELETE /domains/1
  def destroy
    if @domain.destroy
      redirect_to domains_path, notice: t('aliases.deletion-ok')
    else
      render :edit
    end
  end

  private

  def get_domain
    @domain = Domain.find params[:id]
  end

  def domain_params
    params.require(:domain).permit( :o, :associateddomain,
                                    :destinationindicator, :description )
  end

end

app/views/domains/_form.html.erb
<% if @domain.new_record?
  submit_text = t('domains.actions.create')
  submit_url = domains_path
  submit_method = 'post'
else
  submit_text = t('domains.actions.update')
  submit_url = domain_path(@domain.id)
  submit_method = 'put'
end %>

<%= form_with url: submit_url, method: submit_method, local: true do %>
  <%= render partial: 'layouts/errors', locals: {object: @domain} %>
  <div class="col-md-10 col-xs-12">
    <div class="row form-group mt-2"  title="<%= t('ldap.descriptions.o') %>">
      <div class="col-md-3 col-xs-12 text-md-right font-weight-bold">* <%= t("domains.name") %>:</div>
      <div class="col-md-8 col-xs-12">
        <%= text_field :domain, :o, class: "form-control", required: true, disabled: !@domain.new_record? %>
      </div>
    </div>
    <div class="row form-group" title="<%= t('ldap.descriptions.associated-domain') %>">
      <div class="col-md-3 col-xs-12 text-md-right font-weight-bold"><%= t("ldap.attributes.associated-domain") %>:</div>
      <div class="col-md-8 col-xs-12">
        <%= text_field :domain, :associateddomain, class: "form-control" %>
      </div>
    </div>
    <div class="row form-group" title="<%= t('ldap.descriptions.mailbox') %>">
      <div class="col-md-3 col-xs-12 text-md-right font-weight-bold"><%= t("ldap.attributes.mailbox") %>:</div>
      <div class="col-md-8 col-xs-12">
        <%= text_field :domain, :destinationindicator, class: "form-control" %>
      </div>
    </div>
    <div class="row form-group" title="<%= t('ldap.descriptions.description') %>">
      <div class="col-md-3 col-xs-12 text-md-right font-weight-bold"><%= t("ldap.attributes.description") %>:</div>
      <div class="col-md-8 col-xs-12">
        <%= text_field :domain, :description, class: "form-control" %>
      </div>
    </div>
    <div class="float-right">
      <%= submit_tag(submit_text) %>
    </div>
  </div>
<% end %>

  <div class="mt-5 col-md-10 col-xs-12">
    <%= render partial: 'items' unless @domain.new_record? %>
  </div>

app/views/domains/_items.html.erb
    <div class="row mt-4">
      <div class="col-md-3 col-xs-12 text-md-right font-weight-bold"><%= t("domains.people") %>:</div>
      <div class="col-md-8 col-xs-12">
        <%= link_to icon('fa', 'user-edit', t("domains.people-count", count: @domain.people.count)),
                    domain_people_path(@domain.o), title: t('domains.actions.people')%[@domain.o] %>
      </div>
    </div>
    <div class="row mt-2">
      <div class="col-md-3 col-xs-12 text-md-right font-weight-bold"><%= t("domains.groups") %>:</div>
      <div class="col-md-8 col-xs-12">
        <%= link_to icon('fa', 'users', t("domains.groups-count", count: @domain.groups.count)),
                    domain_groups_path(@domain.o), title: t('domains.actions.groups')%[@domain.o] %>
      </div>
    </div>
    <div class="row mt-2">
      <div class="col-md-3 col-xs-12 text-md-right font-weight-bold"><%= t("domains.mail-aliases") %>:</div>
      <div class="col-md-8 col-xs-12">
        <%= link_to icon('fa', 'envelope', t("domains.mail-aliases-count", count: @domain.aliases.count)),
                    domain_aliases_path(@domain.o), title: t('domains.actions.aliases')%[@domain.o] %>
      </div>
    </div>

app/views/domains/edit.html.erb
<% @current_page = t('domains.actions.edit')%[@domain.id] %>
<%= render partial: 'form' %>

app/views/domains/index.html.erb
<% @current_page = t('domains.menu') %>
<% if @domains.any? %>
  <table id="domains-table"
         data-page-length='25'
         class="table table-striped table-bordered table-hover data-table">
    <thead>
      <tr>
        <th><%= t("domains.name") %></th>
        <th data-orderable='false'>&nbsp;</th>
        <th data-orderable='false'>&nbsp;</th>
      </tr>
    </thead>
      <tbody>
        <% @domains.each do |domain| %>
          <% show_url = domain_path(domain.id) %>
          <% show_title = t('domains.actions.show')%[domain.id] %>
          <tr>
            <td data-href="<%= show_url %>">
              <a href="<%= show_url %>" title="<%= show_title %>">
                <%= domain.o %>
                <% if domain.o != domain.associatedDomain %>
                  &nbsp;
                  <%= icon('fa', 'share', title: t('domains.mail-redirected-to')%[domain.associatedDomain]) %>
                <% end %>
              </a>
            </td>
            <td data-href="<%= show_url %>">
              <%= domain.description %>
            </td>
            <td class="text-right">
              <%= link_to icon('fa', 'edit'), edit_domain_path(domain.id), title: t('domains.actions.edit')%[domain.id] %>
              <%= link_to icon('fa', 'trash'), domain_path(domain.id), method: :delete,
                          data: {confirm: t('domains.actions.delete-confirm')%[domain.id]}, title: t('domains.actions.delete')%[domain.id] %>
            </td>
          </tr>
        <% end %>
      </tbody>
  </table>
<% else %>
  <div class="row">
    <div class="col-md-12"><%= t('domains.no-items') %></div>
  </div>
<% end %>

<div class="float-right mt-5">
  <%= link_to icon('fa', 'globe-europe', t('domains.actions.new')), new_domain_path, title: t('domains.actions.new'), class: 'page-link' %>
</div>

<script>
  $(document).ready(function() {
    $("#domains-table").dataTable();
  });
</script

app/views/domains/new.html.erb
<% @current_page = t('domains.actions.new') %>
<%= render partial: 'form' %>

app/views/domains/show.html.erb
<% @current_page = @domain.id %>
<div class="row">
  <div class="col-md-10 col-xs-12">
    <div class="row mt-2">
      <div class="col-md-3 col-xs-12 text-md-right font-weight-bold"><%= t("domains.name") %>:</div>
      <div class="col-md-8 col-xs-12"><%= @domain.id %></div>
    </div>
    <div class="row mt-2">
      <div class="col-md-3 col-xs-12 text-md-right font-weight-bold"><%= t("ldap.attributes.associated-domain") %>:</div>
      <div class="col-md-8 col-xs-12"><%= @domain.associatedDomain %></div>
    </div>
    <div class="row mt-2">
      <div class="col-md-3 col-xs-12 text-md-right font-weight-bold"><%= t("ldap.attributes.mailbox") %>:</div>
      <div class="col-md-8 col-xs-12"><%= @domain.destinationIndicator %></div>
    </div>
    <div class="row mt-2">
      <div class="col-md-3 col-xs-12 text-md-right font-weight-bold"><%= t("ldap.attributes.description") %>:</div>
      <div class="col-md-8 col-xs-12"><%= @domain.description %></div>
    </div>

    <%= render partial: 'items' %>
  </div>
</div>